---

kind: ConfigMap
apiVersion: v1
metadata:
  name: kanali-tracer-config
  namespace: {{default "default" .Values.kanali.namespace}}
data:
  tracer.yaml: |-
{{toYaml .Values.kanali.gateway.jaeger.config | indent 4}}
